Repository hmcts/em-media-viewer, pull requests merged in 2021-09, with the labels that each got.

#392 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-392

#391 EM-4020-Redact E2E Tests
  e2e/src/features/pdf.viewer.redactions.feature
  e2e/src/pages/app.po.ts
  e2e/src/pages/redact.po.ts
  e2e/src/step_definitions/media-viewer.ts
  e2e/src/step_definitions/redact.ts
Labels: ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-391

#395 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-395

#397 EM-4059-Functional Tests fix
  e2e/src/features/zoom.feature
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-397
