Repository hmcts/em-media-viewer, pull requests merged in 2021-06, with the labels that each got.

#371 fixing nightly build
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-371

#374 working on nightly build
  package.json
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-374

#375 Updating two dependencies for nightly build
  package.json
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-375

#376 add video support
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/media-viewer.component.html
  projects/media-viewer/src/lib/media-viewer.component.ts
  projects/media-viewer/src/lib/media-viewer.module.ts
  projects/media-viewer/src/lib/viewers/audio-player/audio-player.component.html
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.html
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.spec.ts
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.ts
  src/app/media-viewer-wrapper/media-viewer-wrapper.component.html
  src/app/media-viewer-wrapper/media-viewer-wrapper.component.ts
  src/app/media-viewer-wrapper/toolbar-toggles/toolbar-toggles.component.html
  src/app/media-viewer-wrapper/toolbar-toggles/toolbar-toggles.component.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-376
