Repository hmcts/em-media-viewer, pull requests merged in 2022-08, with the labels that each got.

#536 dependency yarn-audit-known-issues 18/08/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-536

#538 Add backstage configuration file
  catalog-info.yaml
Labels: ns:em, prd:em, rel:em-media-viewer-pr-538

#543 dependency yarn-audit-known-issues 31/08/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-543
