Repository hmcts/em-media-viewer, pull requests merged in 2022-01, with the labels that each got.

#426 suppress vulnerabilities to fix the nightly build
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-426

#427 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-427

#403 crossbrowser initial implementation
  .gitignore
  Jenkinsfile_nightly
  e2e/reports.js
  e2e/saucelabs.conf.js
  e2e/src/features/bookmarks.feature
  e2e/src/features/comments.panel.feature
  e2e/src/features/navigation.feature
  e2e/src/features/search.feature
  e2e/src/features/zoom.feature
  e2e/src/pages/commentspanel.po.ts
  e2e/src/step_definitions/media-viewer.ts
  e2e/src/step_definitions/timeout.ts
  package.json
  src/browserslist
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-403

#433 Fix security scan, add Makefile
  Makefile
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-433
