Repository hmcts/em-media-viewer, pull requests merged in 2022-07, with the labels that each got.

#519 pipeline issue fix 06/07/2022
  charts/em-media-viewer/Chart.yaml
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-519

#520 dependency pipeline issue fix 07/07/2022
  package.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-520

#522 Fix the rendering when adding new comments
  projects/media-viewer/src/lib/annotations/annotation-set/ctx-toolbar/ctx-toolbar.component.ts
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-522

#526 dependency pipeline issue fix 14/07/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-526

#527 Suppress vulnerabilities, Update Helm Chart
  charts/em-media-viewer/Chart.yaml
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-527

#528 [EM-4497]-Media Viewer Pipeline fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-528

#529 [EM-4510]-Media Viewer Dependency Check Issue
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-529
