Repository hmcts/em-media-viewer, pull requests merged in 2022-10, with the labels that each got.

#554 [EM-4519]-IDAMApiHelper
  .gitignore
  package.json
  test/config.js
  test/end-to-end/helpers/idamApi.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-554

#555 [EM-4521]-S2S Helper
  Jenkinsfile_nightly
  test/end-to-end/helpers/s2sHelper.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-555

#556 [EM-4520]-CCD DatastoreApi Helper
  test/end-to-end/helpers/ccdDataStoreApi.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-556

#557 [EM-4522]-CCD Casedata Payload
  test/end-to-end/data/ccd-case-basic-data.json
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-557

#558 [EM-4524]- Puppeteer helper
  package.json
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/helpers/WebDriverHelper.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-558

#560 added 14 fingerprints to audit.json for media viewer 06/10/2022 night…
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-560

#561 added 6 further fingerprints to audit.json for media viewer 06/10/202…
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-561

#563 EM-4523 - added codecept.conf.js
  package.json
  test/end-to-end/codecept.conf.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-563

#565 [EM-4654]-MV Securityscan fix
  audit.json
Labels: ns:em, prd:em, dts-em-automation, rel:em-media-viewer-pr-565

#566 [EM-4654]-MV-Securityscan-Fix
  audit.json
Labels: ns:em, prd:em, dts-em-automation, rel:em-media-viewer-pr-566

#550 Em 4555 highlighted more than once
  .gitignore
  package.json
  projects/media-viewer/src/assets/sass/rectangle.scss
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.spec.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.ts
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-550

#569 Em 4663 fix em nightly pipeline 13 10 2022
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-569

#568 [EM-4659]-MV-CodeceptJS-SmokeTest
  Jenkinsfile_CNP
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/ccdDataStoreApi.js
  test/end-to-end/pages/idam/signIn.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/IdamLogin.js
  yarn.lock
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-568

#571 [EM-4668]-MV-DependencyCheckFix
  yarn-audit-known-issues
Labels: ns:em, prd:em, dts-em-automation, rel:em-media-viewer-pr-571

#575 EM-4695 - ran yarn audit dependencies command and added fingerprints …
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-575

#578 [EM-4865]-Create CCD Case For Media Viewer
  Jenkinsfile_CNP
  package.json
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/ccdCaseHelper.js
  test/end-to-end/helpers/ccdDataStoreApi.js
  test/end-to-end/helpers/idamApi.js
  test/end-to-end/helpers/s2sHelper.js
  test/end-to-end/pages/nextStep/nextStep.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/verifyCCDCaseCreation.js
  yarn.lock
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-578

#579 [EM-4584]-Media Viewer Upload Document Scenarios
  package.json
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/data/ThankYou.doc
  test/end-to-end/data/commonConfig.json
  test/end-to-end/data/example.pdf
  test/end-to-end/data/quote.jpg
  test/end-to-end/helpers/ccdCaseHelper.js
  test/end-to-end/helpers/ccdDataStoreApi.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/idam/signIn.js
  test/end-to-end/pages/steps.js
  test/end-to-end/pages/uploadDocument/uploadImageJpeg.js
  test/end-to-end/pages/uploadDocument/uploadPdfDocument.js
  test/end-to-end/pages/uploadDocument/uploadWordDocument.js
  test/end-to-end/paths/verifyCCDCaseCreation.js
  test/end-to-end/paths/verifyDMStoreUploadDocuments.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-579

#580 [EM-4529]-MV Content Search E2E
  functional-output/.gitkeep
  test/end-to-end/data/commonConfig.json
  test/end-to-end/data/example.pdf
  test/end-to-end/helpers/ccdDataStoreApi.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/search/search.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/createCCDCase.js
  test/end-to-end/paths/dmStoreUploadDocuments.js
  test/end-to-end/paths/idamLogin.js
  test/end-to-end/paths/search.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-580

#581 [EM-4718]-MV-Navigate Search results using Next and Previous Links
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/search/contentSearch.js
  test/end-to-end/pages/search/navigateSearchResults.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/search.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-581

#582 [EM-4716]-Search results not found Scenario
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/search/contentSearch.js
  test/end-to-end/paths/search.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-582
