Repository hmcts/em-media-viewer, pull requests merged in 2022-11, with the labels that each got.

#584 EM-4738 - added 5 fingerprints into audit.json. changed package.json …
  audit.json
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-584

#586 [EM-4715]-Enter Should Jump Viewer To Next Search Result
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/search/searchResultsNavigationUsingEnter.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/search.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-586

#587 [EM-4528]-Zoom Feature E2E Tests
  package.json
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/steps.js
  test/end-to-end/pages/zoom/pdfViewerZoom.js
  test/end-to-end/paths/dmStoreUploadDocuments.js
  test/end-to-end/paths/zoom.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-587

#590 [Em-4526]-MV Key Vaults config update for nightly pipeline
  Jenkinsfile_nightly
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-590

#592 [EM-4538]-Migrate MV Download Tests
  package.json
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/downloadAndPrint.js
  test/end-to-end/mvFeatures/uploadDocument.js
  test/end-to-end/mvFeatures/zoomAndnavigation.js
  test/end-to-end/pages/downloadAndPrint/mvDownload.js
  test/end-to-end/pages/downloadAndPrint/mvPrint.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-592

#594 EM-4781 - added further dependencies into yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-594

#596 [EM-4785] Rotate pdf viewer
  package.json
  test/config.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/pages/bookMarks/createBookmarks.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-596

#599 [EM-4799]-Delete Bookmark Test
  package.json
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/pages/bookMarks/clearBookmarkss.js
  test/end-to-end/pages/bookMarks/deleteBookMark.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-599

#600 [EM-4803]-Update A Bookmark Test
  test/config.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/mvFeatures/createCCDCase.js
  test/end-to-end/mvFeatures/downloadAndPrint.js
  test/end-to-end/mvFeatures/pdfAndImageRotation.js
  test/end-to-end/mvFeatures/search.js
  test/end-to-end/mvFeatures/uploadDocument.js
  test/end-to-end/mvFeatures/zoomAndnavigation.js
  test/end-to-end/pages/bookMarks/updateBookMark.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-600

#601 [EM-4804]-Create an empty bookmarks test
  package.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/pages/bookMarks/addAnEmptyBookMarks.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-601

#602 [EM-4540]-Multi Media Audio E2E Tests
  test/end-to-end/data/ccd-case-basic-data.json
  test/end-to-end/data/commonConfig.json
  test/end-to-end/data/nicemelody.mp3
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/multiMediaAudioAndVideo.js
  test/end-to-end/mvFeatures/search.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/multiMediaAudioAndVideo/multiMediaAudio.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-602

#603 [EM-4791]-Enable Page Navigation Based On User Input
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/zoomAndnavigation.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/navigationMV/pdfViewerNavigation.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-603

#605 EM-4830 - added dependency into yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-605

#574 EM-3442: Fixing the overlay issues
  projects/media-viewer/src/lib/viewers/image-viewer/image-viewer.component.html
Labels: ns:em, prd:em, rel:em-media-viewer-pr-574

#607 [EM-4845]-Enable MV Functional Tests
  package.json
  test/config.js
  test/end-to-end/mvFeatures/downloadAndPrint.js
  test/end-to-end/mvFeatures/pdfViewerAnnotations.js
Labels: ns:em, prd:em, dts-em-automation, rel:em-media-viewer-pr-607
