Repository hmcts/em-media-viewer, pull requests merged in 2022-12, with the labels that each got.

#609 [EM-4847]-Delete Annotation
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/mvFeatures/printAndDownload.js
  test/end-to-end/mvFeatures/rotate.js
  test/end-to-end/mvFeatures/zoomAndnavigation.js
  test/end-to-end/pages/annotationsAndComments/addComment.js
  test/end-to-end/pages/annotationsAndComments/clearExistingTextHighlights.js
  test/end-to-end/pages/annotationsAndComments/deleteAnnotations.js
  test/end-to-end/pages/annotationsAndComments/deleteExistingComments.js
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/printAndDownload/mvDownload.js
  test/end-to-end/pages/printAndDownload/mvPrint.js
  test/end-to-end/pages/rotate/pdfAndImageRotation.js
  test/end-to-end/pages/steps.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-609

#613 [EM-4861]-Update A Comment Test
  package.json
  test/config.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/pages/annotationsAndComments/addComment.js
  test/end-to-end/pages/annotationsAndComments/addComments.js
  test/end-to-end/pages/annotationsAndComments/clickCommentsPanel.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingTextHighlights.js
  test/end-to-end/pages/annotationsAndComments/deleteAnnotations.js
  test/end-to-end/pages/annotationsAndComments/deleteComments.js
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/highLightPdfText/highLighText.js
  test/end-to-end/pages/steps.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-613

#614 [EM-4863]-Collate Comments Test
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/pages/annotationsAndComments/collateComments.js
  test/end-to-end/pages/annotationsAndComments/commentsSearch.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/steps.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-614

#617 [EM-4575]-Execute Cross browser Tests
  Jenkinsfile_nightly
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/pages/navigationMV/pdfViewerNavigation.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-617

#619 [EM-4868]-Add Multiple Comments On Multiple Pages
  Jenkinsfile_nightly
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/pages/annotationsAndComments/addMultipleComments.js
  test/end-to-end/pages/navigationMV/pdfViewerNavigation.js
  test/end-to-end/pages/steps.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-619

#621 EM-4888 - added dependency into yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-621

#623 [EM-4892]-Enable MV Tests
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/mvFeatures/dmStoreScenarios.js
  test/end-to-end/mvFeatures/indexAndOutline.js
  test/end-to-end/mvFeatures/search.js
  test/end-to-end/pages/dmStore/uploadImageJpeg.js
  test/end-to-end/pages/dmStore/uploadPdfDocument.js
  test/end-to-end/pages/dmStore/uploadWordDocument.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-623

#625 [EM-4886]-Mark Content For Redaction Using Draw Box Function
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/redact/markContentForRedaction.js
  test/end-to-end/pages/redact/redactContentUsingDrawBox.js
  test/end-to-end/pages/redact/redactTextUsingDrawBox.js
  test/end-to-end/pages/redact/verifyWhetherTheRedactionAreVisibleOrNot.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-625

#626 [EM-4894]-Redact Scenarios
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/mvFeatures/smokeTest.js
  test/end-to-end/pages/redact/CreateRedactionsUsingDrawboxAndRedactText.js
  test/end-to-end/pages/redact/previewAllRedactions.js
  test/end-to-end/pages/redact/redactTextAndThenRemoveRedaction.js
  test/end-to-end/pages/redact/saveAllRedactions.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-626

#628 [EM-4903]-Execute MV Functional Tests In Local Environment
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/mvCaseHelper.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-628

#631 [EM-4913]-Bookmark Tests Execution in Preview Environment
  test/config.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/mvFeatures/multiMedia.js
  test/end-to-end/mvFeatures/search.js
  test/end-to-end/mvFeatures/zoomAndnavigation.js
  test/end-to-end/pages/idam/signIn.js
  test/end-to-end/pages/multiMedia/multiMediaAudio.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-631

#632 [EM-4915]-updated test execution of preview env
  test/config.js
  test/end-to-end/helpers/mvCaseHelper.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-632
