Repository hmcts/em-media-viewer, pull requests merged in 2022-03, with the labels that each got.

#452 bump nodejs chart
  charts/em-media-viewer/Chart.yaml
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-452

#453 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-453

#455 Fix nightly build
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-455

#454 [EM-4280]-Multimedia Audio Scenarios
  e2e/src/features/multimedia.audio.feature
  e2e/src/features/multimedia.feature
  e2e/src/step_definitions/multimedia.ts
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-454

#458 Fix nightly build
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-458

#459 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-459

#460 pipeline issue fix 24/03/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-460

#461 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-461

#462 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-462
