Repository hmcts/em-media-viewer, pull requests merged in 2022-04, with the labels that each got.

#464 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-464

#465 Upgrade Node Version
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-465

#470 Fix dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-470

#471 Bump the package version to v2.7.12-RC.1
  package.json
  projects/media-viewer/package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-471

#472 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-472

#473 Suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-473

#474 [EM-4392]-MV Cross browser Tests
  e2e/saucelabs.conf.js
  e2e/supportedBrowsers.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-474

#476 [EM-4401]-Media Viewer Dependency Check fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-476
