Repository hmcts/em-media-viewer, pull requests merged in 2022-09, with the labels that each got.

#544 Use dev dependencies
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-544

#545 Change document id
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.spec.ts
  src/app/media-viewer-wrapper/media-viewer-wrapper.component.ts
  src/assets/documents/image/69fb7313-5338-42c4-b94d-0ceb3b6ed18b
  src/assets/documents/pdf/7547364e-5e49-452b-82e9-8d4b8a334a53
Labels: ns:em, prd:em, rel:em-media-viewer-pr-545

#547 [EM-4591]-Media Viewer Dependency Check Fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, EM-Automation, rel:em-media-viewer-pr-547

#548 dependency yarn-audit-known-issues 15/09/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-548

#549 dependency yarn-audit-known-issues 20/09/2022
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-549
