Repository hmcts/em-media-viewer, pull requests merged in 2023-10, with the labels that each got.

#820 em-5576: added fingerprints to audit.json
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-820

#821 em-5578: added fingerprints and dependency check
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-821

#822 em-5580: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-822

#828 em-5582: added fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-828

#829 em-5583: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-829

#830 em-5584: added fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-830

#788 em-4973: automation - bookmarks
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/pages/bookMarks/add30Bookmarks.js
  test/end-to-end/pages/steps.js
Labels: DO NOT MERGE, ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-788

#787 em-4705: new automation - bookMarks
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/pages/bookMarks/bookmarkBoxBlank.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-787

#834 em-5589: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-834

#789 em-4946: automation - comment summary
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/pages/annotationsAndComments/addMultipleComments.js
  test/end-to-end/pages/annotationsAndComments/collateCommentsNotBlank.js
  test/end-to-end/pages/steps.js
Labels: DO NOT MERGE, ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-789

#790 prevent loading of annotations and redactions for multimedia
  projects/media-viewer/src/lib/media-viewer.component.ts
Labels: DO NOT MERGE, ns:em, prd:em, rel:em-media-viewer-pr-790

#835 em-5590: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-835

#773 em-4283: new HRS Platform e2e test added
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/hrsPlatform.js
  test/end-to-end/pages/hrsPlatform/findCase.js
  test/end-to-end/pages/hrsPlatform/hrsSignIn.js
  test/end-to-end/pages/hrsPlatform/shareHRSFile.js
  test/end-to-end/pages/steps.js
Labels: DO NOT MERGE, ns:em, prd:em, rel:em-media-viewer-pr-773

#836 em-5592: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-836

#838 em-5595: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-838

#842 update links for functional tests
  Jenkinsfile_nightly
  test/end-to-end/helpers/mvCaseHelper.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-842

#843 Fix failing tests
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/imageViewer/openImage.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-843

#845 em-5599: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-845

#846 em-5602: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-846

#847 em-5606: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-847

#848 prevent unit tests running 3 times
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-848

#850 em-5607: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-850

#854 em-5609: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-854

#855 em-5612: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-855

#860 em-5615: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-860

#866 em-5619: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-866

#869 update node chart
  charts/em-media-viewer/Chart.yaml
Labels: ns:em, prd:em, rel:em-media-viewer-pr-869

#785 Em 5348 accessibility issue
  projects/media-viewer/src/assets/sass/outline-attachment.scss
  projects/media-viewer/src/assets/sass/toolbar/main-toolbar.scss
  projects/media-viewer/src/assets/sass/toolbar/search-bar.scss
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-set-header.component.html
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.html
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.html
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.ts
  projects/media-viewer/src/lib/viewers/image-viewer/image-viewer.component.html
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/search/contentSearch.js
  test/end-to-end/pages/search/enterShouldJumpViewerToNextSearchResults.js
  test/end-to-end/pages/search/searchResultsNavigationUsingNextAndPrevious.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-785
