Repository hmcts/em-media-viewer, pull requests merged in 2023-01, with the labels that each got.

#635 [EM-4925]-Annotations And Comments Tests Execution In Preview Env
  Jenkinsfile_CNP
  test/config.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-635

#636 [EM-4934]-Execute Index And Outline Scripts in Preview Env
  test/end-to-end/codecept.conf.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-636

#642 [EM-4937]-MV-Nightly Build Fix
  Jenkinsfile_nightly
  e2e/saucelabs.conf.js
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/codecept.smoke.conf.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/smokeTest.js
  test/end-to-end/pages/idam/signIn.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, em-support, rel:em-media-viewer-pr-642

#643 EM-4944 added new fingerprints into audit.json, as well as additional…
  audit.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/mvCaseHelper.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-643

#645 [EM-4931]-Search Scripts Execution In Preview
  test/config.js
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/indexAndOutline.js
  test/end-to-end/mvFeatures/search.js
  test/end-to-end/pages/common/constants.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-645

#644 em-4944- added new fingerprints into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-644

#647 [EM-4930]-Redact Tests Execution On Preview
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/annotationsAndComments.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/redact/redactText.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-647

#650 em-4944- added 1 new fingerprint into audit.json. ran yarn audit command
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-650

#649 [EM-4932]-Zoom And Rotate Tests Execution On Preview
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/openCaseDocsInMv/openCaseDocsInMV.js
  test/end-to-end/pages/redact/verifyWhetherTheRedactionAreVisibleOrNot.js
Labels: ns:em, prd:em, migrate-protractor-framework-to-codeceptjs, rel:em-media-viewer-pr-649

#639 Em 4651 azure web public changes
  projects/media-viewer/src/lib/icp/icp-presenter.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-session-api.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-update.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-update.service.ts
  projects/media-viewer/src/lib/icp/icp.events.ts
  projects/media-viewer/src/lib/icp/icp.interfaces.ts
  projects/media-viewer/src/lib/icp/icp.service.spec.ts
  projects/media-viewer/src/lib/icp/socket.service.spec.ts
  projects/media-viewer/src/lib/icp/socket.service.ts
  projects/media-viewer/src/lib/store/actions/icp.actions.spec.ts
  projects/media-viewer/src/lib/store/effects/icp.effects.spec.ts
  projects/media-viewer/src/lib/store/reducers/icp.reducer.spec.ts
  projects/media-viewer/src/lib/store/selectors/icp.selectors.spec.ts
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  sonar-project.properties
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-639

#651 em-4944- added 7 new fingerprints into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-651

#652 [EM-4952]-MV Master build fix
  audit.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-652

#653 [EM-4952]-Security Scan Fix
  audit.json
  security.sh
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-653

#646 FIlter out unsaved comments
  projects/media-viewer/src/lib/store/selectors/annotation.selectors.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-646

#627 Add page numbers to outline and highlight current section
  projects/media-viewer/src/assets/sass/outline-attachment.scss
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline-item.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline-item.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline-item.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline.model.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.ts
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/indexAndOutline.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/indexAndOutline/navigateIndexBundleDocument.js
  test/end-to-end/pages/indexAndOutline/navigateIndexNestedDocument.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-627

#658 [EM-4962]-Media Viewer Functional Tests Fix
  test/end-to-end/mvFeatures/indexAndOutline.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-658

#660 [EM-4967]-ExUI SRT Execution On Nightly Pipeline
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/idam/signIn.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-660

#654 update the icp url
  Jenkinsfile_CNP
  charts/em-media-viewer/Chart.yaml
  charts/em-media-viewer/values.yaml
Labels: ns:em, prd:em, rel:em-media-viewer-pr-654

#663 [EM-4971]-MV Cross browser Tests Fix
  Jenkinsfile_nightly
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/common/constants.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-663

#665 [EM-4987]-MV Dependency Check Fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-665

#669 [EM-4997]-Media Viewer Dependency Check Fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-669

#670 [EM-5000]-ExUI-SRT-Fix
  test/config.js
  test/end-to-end/mvFeatures/smokeTest.js
  test/end-to-end/pages/idam/signIn.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-670

#673 [EM-5004]-Media Viewer Master Build Functional Tests Fix
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/idam/signIn.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-673

#674 [EM-5004]-MV Functional Tests Fix
  test/end-to-end/codecept.conf.js
Labels: ns:em, prd:em, em-support, rel:em-media-viewer-pr-674

#671 Upgrade angular to version 8
  .github/workflows/npmpublish.yml
  .gitignore
  README.md
  angular.json
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/assets/sass/comment.scss
  projects/media-viewer/src/assets/sass/participants-list.scss
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/box-highlight-create/box-highlight-create.component.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-view/annotation-view.component.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-view/rectangle/rectangle.component.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-navigate/comments-navigate.component.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-search/comment-search.component.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-search/commet-search.component.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set.component.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.ts
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.ts
  projects/media-viewer/src/lib/media-viewer.component.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.ts
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.ts
  projects/media-viewer/src/lib/viewers/image-viewer/image-viewer.component.ts
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  projects/media-viewer/src/lib/viewers/unsupported-viewer/unsupported-viewer.component.ts
  src/app/app.component.scss
  src/app/media-viewer-wrapper/custom-toolbar/custom-toolbar.component.ts
  src/app/media-viewer-wrapper/custom-toolbar/search-bar/search-bar.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-671

#675 Upgrade angular to version 9
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-set-header.component.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set.component.spec.ts
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.spec.ts
  projects/media-viewer/src/lib/annotations/services/annotation-api/annotation-api.service.spec.ts
  projects/media-viewer/src/lib/annotations/services/bookmarks-api/bookmarks-api.service.spec.ts
  projects/media-viewer/src/lib/annotations/services/tags/tags.service.spec.ts
  projects/media-viewer/src/lib/icp/confirm-exit/confirm-action-dialog.component.spec.ts
  projects/media-viewer/src/lib/icp/icp-follower.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-presenter.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-session-api.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-update.service.spec.ts
  projects/media-viewer/src/lib/icp/icp.service.spec.ts
  projects/media-viewer/src/lib/icp/participants-list/participants-list.component.spec.ts
  projects/media-viewer/src/lib/media-viewer.component.spec.ts
  projects/media-viewer/src/lib/redaction/services/redaction-api.service.spec.ts
  projects/media-viewer/src/lib/store/effects/annotation.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/bookmarks.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/document.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/icp.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/redaction.effects.spec.ts
  projects/media-viewer/src/lib/store/reducers/bookmarks.reducer.spec.ts
  projects/media-viewer/src/lib/store/reducers/tags.reducer.ts
  projects/media-viewer/src/lib/store/selectors/annotation.selectors.spec.ts
  projects/media-viewer/src/lib/store/selectors/bookmark.selectors.spec.ts
  projects/media-viewer/src/lib/store/selectors/document.selectors.spec.ts
  projects/media-viewer/src/lib/store/selectors/icp.selectors.spec.ts
  projects/media-viewer/src/lib/store/selectors/tag.selectors.spec.ts
  projects/media-viewer/src/lib/toolbar/icp-toolbar/icp-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.spec.ts
  projects/media-viewer/src/lib/viewers/convertible-content-viewer/document-conversion-api.service.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.spec.ts
  projects/media-viewer/src/lib/viewers/rotation-persist/rotation-api.service.spec.ts
  projects/media-viewer/src/lib/viewers/viewer-util.service.spec.ts
  projects/media-viewer/src/public_api.ts
  projects/media-viewer/tsconfig.lib.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-675

#676 Upgrade to angular 10
  angular.json
  e2e/tsconfig.e2e.json
  package.json
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/tsconfig.lib.json
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-676

#677 Upgrade to angular 11
  angular.json
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/annotations/pipes/date/date.pipe.ts
  projects/media-viewer/src/lib/icp/participants-list/participants-list.component.spec.ts
  projects/media-viewer/tsconfig.lib.json
  src/app/app.component.spec.ts
  src/app/routing.module.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-677

#678 EM-5019-fix-pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-media-viewer-pr-678
