Repository hmcts/em-media-viewer, pull requests merged in 2023-07, with the labels that each got.

#757 Em 5315 delete comments
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-757

#758 added new Scenario to redact.js
  test/end-to-end/mvFeatures/redact.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-758

#759 em-5376: added two fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-759

#760 em-5377: added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-760

#762 Em 5315 delete comments
  test/end-to-end/mvFeatures/annotationsAndComments.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-762

#763 Em 5315 delete comments
  test/end-to-end/mvFeatures/redact.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-763

#769 em-5404: dependency check and added 3 fingerprints
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-769

#772 em-5416: added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-772

#774 em-5419: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-774

#775 em-5420: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-775

#776 handle 204 when load annotation set
  projects/media-viewer/src/lib/store/effects/annotation.effects.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-776

#777 em-5424: added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-777
