Repository hmcts/em-media-viewer, pull requests merged in 2023-09, with the labels that each got.

#809 em-5554: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-809

#810 em-5556: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-810

#811 em-5559: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-811

#812 em-5564: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-812

#813 em-5565: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-813

#814 Add renovate file
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-814
