Repository hmcts/em-media-viewer, pull requests merged in 2023-04, with the labels that each got.

#703 Em 5190 fix functional tests
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-703

#704 Fix redaction tests
  .github/workflows/npmpublish.yml
  test/end-to-end/data/commonConfig.json
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/redact/CreateRedactionsUsingDrawboxAndRedactText.js
  test/end-to-end/pages/redact/clearAllRedactions.js
  test/end-to-end/pages/redact/clickRedactMenu.js
  test/end-to-end/pages/redact/markContentForRedaction.js
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-704

#666 EM-4693 fix bookmark remove
  projects/media-viewer/src/lib/store/reducers/bookmarks.reducer.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-666

#690 Fix collated comments when printing comments summary
  projects/media-viewer/src/lib/print.service.spec.ts
  projects/media-viewer/src/lib/print.service.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-690

#695 EM-2668 redact searched text
  package.json
  projects/media-viewer/src/assets/sass/toolbar/main-toolbar.scss
  projects/media-viewer/src/lib/media-viewer.component.html
  projects/media-viewer/src/lib/media-viewer.component.ts
  projects/media-viewer/src/lib/redaction/services/redaction-api.service.spec.ts
  projects/media-viewer/src/lib/redaction/services/redaction-api.service.ts
  projects/media-viewer/src/lib/redaction/services/redaction.model.ts
  projects/media-viewer/src/lib/store/actions/redaction.actions.ts
  projects/media-viewer/src/lib/store/effects/redaction.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/redaction.effects.ts
  projects/media-viewer/src/lib/store/reducers/redaction.reducer.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.ts
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.scss
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.ts
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search.model.ts
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.ts
  projects/media-viewer/src/lib/toolbar/toolbar-event.service.ts
  projects/media-viewer/src/lib/toolbar/toolbar.module.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  src/app/media-viewer-wrapper/media-viewer-wrapper.component.html
  src/app/media-viewer-wrapper/media-viewer-wrapper.component.ts
  src/app/media-viewer-wrapper/toolbar-toggles/toolbar-toggles.component.html
  src/app/media-viewer-wrapper/toolbar-toggles/toolbar-toggles.component.ts
  test/end-to-end/codecept.conf.js
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/redact/clickRedactAllButton.js
  test/end-to-end/pages/redact/clickRedactSearchButton.js
  test/end-to-end/pages/redact/clickSearchFrom.js
  test/end-to-end/pages/redact/redactFillSearchInput.js
  test/end-to-end/pages/redact/redactSearchAndRedctAll.js
  test/end-to-end/pages/steps.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-695

#685 EM-5031: Upgrade Media Viewer use Yarn V3
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  projects/media-viewer/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  projects/media-viewer/.yarn/releases/yarn-3.4.1.cjs
  projects/media-viewer/.yarnrc.yml
  projects/media-viewer/ng-package.json
  projects/media-viewer/ng-package.prod.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/box-highlight-create/box-highlight-create.component.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.service.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-view/annotation-view.component.ts
  projects/media-viewer/src/lib/annotations/annotation-set/metadata-layer/metadata-layer.component.ts
  projects/media-viewer/src/lib/redaction/components/redaction.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.ts
  projects/media-viewer/yarn.lock
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-685

#708 em-5210-deleted security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-media-viewer-pr-708

#709 em-5210-added into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-709

#710 em-5210-added into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-710

#711 em-5210-added into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-711

#713 em-5226-added into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-713
