Repository hmcts/em-media-viewer, pull requests merged in 2023-06, with the labels that each got.

#733 EM-5291: Snow incident INC5509270 - RE: Can't scroll down (still)
  projects/media-viewer/src/assets/sass/toolbar/side-bar.scss
Labels: ns:em, prd:em, rel:em-media-viewer-pr-733

#737 em-5309 - added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-737

#739 em-5312: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-739

#742 copy lockfile
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-742

#744 em-5317: added 4 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-744

#746 em-5320: added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-746

#747 em-5321: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-747

#748 fix master
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-748

#749 The user is able to access document bundles using Safari web browser on laptops and desktops.
  .vscode/settings.json
  projects/media-viewer/src/assets/sass/toolbar/main-toolbar.scss
  projects/media-viewer/src/lib/print.service.spec.ts
  projects/media-viewer/src/lib/print.service.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.html
Labels: ns:em, prd:em, rel:em-media-viewer-pr-749

#752 em-5343 added one fingerprint into audit.json and yarn-audit-known-is…
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-752

#750 print issues on control print
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-750

#754 em-5360 added 3 fingerprints into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-754

#755 add wait
  test/end-to-end/pages/annotationsAndComments/addCommentAndRotate.js
  test/end-to-end/pages/annotationsAndComments/addComments.js
  test/end-to-end/pages/openCaseDocsInMv/openCaseDocsInMV.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-755

#756 waiting for the element to show up
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-756
