Repository hmcts/em-media-viewer, pull requests merged in 2023-05, with the labels that each got.

#699 Em 4599 fix overlapping comments section
  projects/media-viewer/src/assets/sass/comment.scss
  projects/media-viewer/src/lib/annotations/annotations.module.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-set-header.component.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-set-header.component.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.service.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.service.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-699

#693 fix image comments display
  projects/media-viewer/src/assets/sass/comment-set-panel.scss
  projects/media-viewer/src/assets/sass/image-viewer.scss
  projects/media-viewer/src/lib/viewers/image-viewer/image-viewer.component.html
Labels: ns:em, prd:em, rel:em-media-viewer-pr-693

#716 em-5261
  .nvmrc
Labels: ns:em, prd:em, rel:em-media-viewer-pr-716

#718 em-5262-fix-security-scan
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-718

#719 em-5262
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-719

#717 highlight all outline on current page
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline-item.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.ts
  test/end-to-end/pages/annotationsAndComments/addComments.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-717

#714 Separate bookmarks
  .nvmrc
  projects/media-viewer/src/assets/images/toolbarButton-bookmarkDark.png
  projects/media-viewer/src/assets/sass/toolbar/main-toolbar.scss
  projects/media-viewer/src/lib/annotations/annotation-set/metadata-layer/metadata-layer.component.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.ts
  projects/media-viewer/src/lib/toolbar/toolbar-event.service.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.ts
  test/end-to-end/data/commonConfig.json
  test/end-to-end/pages/bookMarks/clearBookmarkss.js
  test/end-to-end/pages/bookMarks/deleteBookMark.js
  test/end-to-end/pages/bookMarks/openBookmarksPanel.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-714

#720 em-5271-fix-mv-nightly
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-720

#721 em-5275-fix-mv-nightly
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-721

#723 em-5283 added fingerprints into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-723

#724 em-5286 added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-724

#725 em-5288 added 3 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-725

#726 em-5290 added 1 fingerprint to audit.json - 10096
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-726

#727 em-5293 - added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-727

#728 em-5294 - added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-728

#729 em-5297 added one fingerprint into audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-729

#730 em-5298 - added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-730
