Repository hmcts/em-media-viewer, pull requests merged in 2023-11, with the labels that each got.

#879 try node 16
  .github/workflows/npmpublish.yml
  .nvmrc
Labels: ns:em, prd:em, rel:em-media-viewer-pr-879

#878 Em 5366 day readable missing
  projects/media-viewer/src/lib/shared/gov-uk-date/gov-uk-date.component.html
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-878

#881 em-5642: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-881

#882 em-5643: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-882

#884 em-5650: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-884

#885 em-5651: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-885

#888 em-5655: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-888

#889 em-5656: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-889

#890 Em 4965 automation new tests
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/bookMarks.js
  test/end-to-end/mvFeatures/redact.js
  test/end-to-end/pages/bookMarks/customOrderBookmarks.js
  test/end-to-end/pages/bookMarks/reorderBookmarks.js
  test/end-to-end/pages/redact/redactSearchAndRedactAll.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-890

#891 em-5666: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-891

#892 em-5667: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-892

#893 em-5671: added 2 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-893
