Repository hmcts/em-media-viewer, pull requests merged in 2024-07, with the labels that each got.

#1041 fix functional tests
  projects/media-viewer/src/assets/sass/pdf-viewer.scss
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.spec.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-view/rectangle/rectangle.component.ts
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/pages/annotationsAndComments/addComments.js
  test/end-to-end/pages/annotationsAndComments/addMultipleComments.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingTextHighlights.js
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1041

#1042 fix functional tests
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
  test/end-to-end/pages/bookMarks/createBookmarks.js
  test/end-to-end/pages/redact/redactText.js
  test/end-to-end/pages/redact/verifyWhetherTheRedactionAreVisibleOrNot.js
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1042

#1046 em-6113: fingerprints added
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1046

#1053 make link clickable
  projects/media-viewer/src/assets/sass/pdf-viewer.scss
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1053

#1040 EM-6094: Hover over changes for bookmark on selecting parent bookmark
  projects/media-viewer/src/assets/sass/angular-tree-component.scss
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1040

#1058 em-6118: fingerprint added
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1058

#1035 PED changes to update the pdf
  package.json
  projects/media-viewer/src/lib/icp/icp-follower.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-follower.service.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  projects/media-viewer/src/lib/viewers/viewer-event.service.ts
  yarn.lock
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1035

#1067 em-6122: fingerprints added
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1067

#1068 em-6124: fingerprint added
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1068

#1071 Revert "Revert "EM-6025 (#997)""
  projects/media-viewer/src/lib/icp/icp-presenter.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-session-api.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-session-api.service.ts
  projects/media-viewer/src/lib/icp/icp-update.service.spec.ts
  projects/media-viewer/src/lib/icp/icp-update.service.ts
  projects/media-viewer/src/lib/icp/icp.interfaces.ts
  projects/media-viewer/src/lib/icp/icp.service.spec.ts
  projects/media-viewer/src/lib/icp/icp.service.ts
  projects/media-viewer/src/lib/store/actions/icp.actions.spec.ts
  projects/media-viewer/src/lib/store/actions/icp.actions.ts
  projects/media-viewer/src/lib/store/effects/icp.effects.spec.ts
  projects/media-viewer/src/lib/store/effects/icp.effects.ts
  projects/media-viewer/src/lib/store/reducers/icp.reducer.spec.ts
  projects/media-viewer/src/lib/store/selectors/icp.selectors.spec.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1071

#1072 add fingerprints
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1072

#1073 add fingerprints
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1073

#1074 add fingerprints
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1074

#1070 changes for the bookmark scroll bar
  projects/media-viewer/src/lib/store/actions/bookmark.actions.spec.ts
  projects/media-viewer/src/lib/store/actions/bookmark.actions.ts
  projects/media-viewer/src/lib/store/reducers/bookmarks.reducer.spec.ts
  projects/media-viewer/src/lib/store/reducers/bookmarks.reducer.ts
  projects/media-viewer/src/lib/store/selectors/bookmark.selectors.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/bookmarks/bookmarks.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1070

#1076 EM-6060: Sometimes when zoom dropdown is clicked - the zoom out is focused
  projects/media-viewer/src/assets/sass/toolbar/main-toolbar.scss
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1076

#1077 #EM-6136: Remove Idam default key from Prop files for em-media-viewer
  api/config.ts
  api/security/idam-client.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1077
