Repository hmcts/em-media-viewer, pull requests merged in 2024-08, with the labels that each got.

#1079 use new mv nightly link
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1079

#1082 Em 6169 update audit
  Jenkinsfile_nightly
  audit.json
  test/config.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1082

#1094 EM-6196 : Investigate Copy paste issue for Media Viewer
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.provider.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1094

#1095 Em 6200 fix mv nightly
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1095

#1096 em-6202: added 1 fingerprint
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1096

#1097 em-6204: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1097

#1100 em-6216: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1100
