Repository hmcts/em-media-viewer, pull requests merged in 2024-04, with the labels that each got.

#961 alter test to increase coverage
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-961

#962 add fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-962

#963 add fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-963

#964 add fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-964

#959 EM-5926: changes for cve
  charts/em-media-viewer/Chart.yaml
  config/dependency-check-suppressions.xml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-959

#966 adding new fingerprints to audit json ignore
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-966

#969 em-5967: dependency check fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-969

#970 Enabling spot instances
  charts/em-media-viewer/Chart.yaml
  charts/em-media-viewer/values.yaml
Labels: ns:em, prd:em, rel:em-media-viewer-pr-970
