Repository hmcts/em-media-viewer, pull requests merged in 2024-01, with the labels that each got.

#883 EM-5647: load docx conrrectly
  projects/media-viewer/src/lib/viewers/convertible-content-viewer/convertible-content-viewer.component.spec.ts
  projects/media-viewer/src/lib/viewers/convertible-content-viewer/convertible-content-viewer.component.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-883

#896 EM-5700 translation
  package.json
  projects/media-viewer/src/lib/annotations/annotations.module.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-filter/comment-filter.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-search/comment-search.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-search/commet-search.component.spec.ts
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.spec.ts
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.html
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.spec.ts
  projects/media-viewer/src/lib/icp/icp-presenter.service.spec.ts
  projects/media-viewer/src/lib/icp/socket.service.spec.ts
  projects/media-viewer/src/lib/media-viewer.component.spec.ts
  projects/media-viewer/src/lib/media-viewer.module.ts
  projects/media-viewer/src/lib/redaction/components/redaction.component.spec.ts
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/main-toolbar/main-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-toolbar/redaction-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/toolbar.module.ts
  projects/media-viewer/src/lib/viewers/image-viewer/image-viewer.component.spec.ts
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.html
  projects/media-viewer/src/lib/viewers/multimedia-player/multimedia-player.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.html
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/side-bar.component.html
  src/app/app.module.ts
  yarn.lock
Labels: DO NOT MERGE, ns:em, prd:em, rel:em-media-viewer-pr-896

#904 em-5760: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-904

#906 bug fixes for accessiblity
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.html
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.spec.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-906

#907 Em 5348 bug fixes
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.html
Labels: ns:em, prd:em, rel:em-media-viewer-pr-907

#909 em-5771: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-909

#911 EM-5364 - fix validation on comments for filter comments
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.html
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.spec.ts
  projects/media-viewer/src/lib/annotations/comments-summary/comments-summary.component.ts
  projects/media-viewer/src/lib/shared/gov-uk-date/gov-uk-date.component.html
Labels: ns:em, prd:em, rel:em-media-viewer-pr-911

#912 em-5774: add fingerprints and dependency check
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-912

#914 em-5783: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-914

#915 EM-5785: highlight not working
  projects/media-viewer/src/lib/annotations/annotation-set/metadata-layer/metadata-layer.component.ts
  projects/media-viewer/src/lib/viewers/rotation-persist/rotation-persist.directive.ts
Labels: ns:em, prd:em, rel:em-media-viewer-pr-915

#916 em-5797: dependency check & fingerprints added
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-916

#917 em-5802: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-917

#918 em-5804: fix to audit.json file
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-918
