Repository hmcts/em-media-viewer, pull requests merged in 2024-06, with the labels that each got.

#1002 em-6056: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1002

#991 Em 5961 angular 17
  .gitignore
  angular.json
  package.json
  projects/media-viewer/ng-package.json
  projects/media-viewer/ng-package.prod.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/box-highlight-create/box-highlight-create.component.spec.ts
  projects/media-viewer/src/lib/icp/socket.service.ts
  projects/media-viewer/src/lib/media-viewer.component.ts
  projects/media-viewer/src/lib/toolbar/icp-event.service.ts
  projects/media-viewer/src/lib/toolbar/toolbar-event.service.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.spec.ts
  projects/media-viewer/src/lib/viewers/viewer-event.service.ts
  projects/media-viewer/tsconfig.lib.json
  projects/media-viewer/yarn.lock
  src/app/app.component.spec.ts
  src/app/app.module.ts
  test/end-to-end/helpers/ccdDataStoreApi.js
  test/end-to-end/helpers/idamApi.js
  test/end-to-end/helpers/s2sHelper.js
  yarn.lock
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-991

#1028 em-6072: added fingerprints
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1028

#1034 em-6080: dependency check
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1034

#998 Em 6035 upgrade pdfjs
  .eslintrc.json
  package.json
  projects/media-viewer/.eslintrc.json
  projects/media-viewer/package.json
  projects/media-viewer/src/assets/sass/pdf-viewer.scss
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.spec.ts
  projects/media-viewer/src/lib/annotations/annotation-set/annotation-create/highlight-create/highlight-create.directive.ts
  projects/media-viewer/src/lib/store/reducers/document.reducer.ts
  projects/media-viewer/src/lib/store/selectors/bookmark.selectors.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.provider.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.provider.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.html
  projects/media-viewer/yarn.lock
  test/end-to-end/data/commonConfig.json
  test/end-to-end/pages/annotationsAndComments/deleteAllExistingComments.js
  test/end-to-end/pages/annotationsAndComments/highlightPdfText.js
  test/end-to-end/pages/bookMarks/createBookmarks.js
  test/end-to-end/pages/redact/clearAllRedactions.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-998
