Repository hmcts/em-media-viewer, pull requests merged in 2024-03, with the labels that each got.

#946 em-5886: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-946

#947 em-5888: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-947

#952 em-5901: dependency check fix and added fingerprints
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-952

#953 outline not found fails on load doc
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-953

#954 em-5913: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-954

#955 em-5919: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-955

#956 EM-5911: MV: BDD for Need a scenario where there are no outline on t…
  test/end-to-end/data/commonConfig.json
  test/end-to-end/helpers/mvCaseHelper.js
  test/end-to-end/mvFeatures/indexAndOutline.js
  test/end-to-end/pages/common/constants.js
  test/end-to-end/pages/indexAndOutline/loadDocumentAndCheckSuccessLoad.js
  test/end-to-end/pages/steps.js
Labels: ns:em, prd:em, rel:em-media-viewer-pr-956

#958 em-5928: dependency check fix and added fingerprint
  audit.json
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-958
