Repository hmcts/em-media-viewer, pull requests merged in 2024-02, with the labels that each got.

#900 em-4284: pa11y new config file
  .pa11yci2
  pa11y/pa11y-screenshots/home.png
Labels: ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-900

#913 EM-5764: clicking 'prev' button in 'search', the 'next' button becomes the focus
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.ts
  projects/media-viewer/src/lib/toolbar/toolbar-event.service.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-913

#919 Em 5811 fix mv nightly - added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-919

#922 em-5814: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-922

#923 em-5816: fix to Redaction test
  test/end-to-end/data/commonConfig.json
  test/end-to-end/pages/redact/clickRedactAllButton.js
Labels: QA-Automation

#925 em-5817: assert redact search switch
  test/end-to-end/data/commonConfig.json
  test/end-to-end/pages/redact/clickSearchFrom.js
Labels: QA-Automation

#927 em-5824: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-927

#930 em-5827: added fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-930

#933 EM-5829: pdfjs-dist upgrade to 4 from 2
  package.json
  projects/media-viewer/src/lib/toolbar/highlight-toolbar/highlight-toolbar.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.provider.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-js/pdf-js-wrapper.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/pdf-viewer.component.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline-item.component.spec.ts
  projects/media-viewer/src/lib/viewers/pdf-viewer/side-bar/outline-item/outline.model.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-933

#805 em-4957: testing core functionality - smoke test
  test/end-to-end/mvFeatures/smokeTest.js
Labels: DO NOT MERGE, ns:em, prd:em, QA-Automation, rel:em-media-viewer-pr-805

#940 em-5840: dependency check fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-940

#941 em-5847: dependency check fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-941

#942 Revert changes
  package.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-942

#944 EM-5841 : print not work
  projects/media-viewer/src/lib/print.service.ts
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-944
