Repository hmcts/em-media-viewer, pull requests merged in 2025-08, with the labels that each got.

#1193 Ex UI 3395 nightly pipeline fix
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1193

#1197 EXUI-3331 Investigate and Add Missing MIT Licences to Repositories
  LICENCE
  LICENSE
  package.json
Labels: enable_keep_helm

#1175 Tech/ex UI 477 govuk frontend upgrade
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/assets/sass/settings.scss
  src/app/app.component.scss
  yarn.lock
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1175
