Repository hmcts/em-media-viewer, pull requests merged in 2025-05, with the labels that each got.

#1174 EXUI-3704: update audit file
  yarn-audit-known-issues
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1174

#1170 Task/ex UI 2993 upgrade 18
  api/security/token-repository.ts
  api/server.ts
  package.json
  projects/media-viewer/package.json
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-filter/comment-filter.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment-set-header/comment-search/comment-search.component.html
  projects/media-viewer/src/lib/annotations/comment-set/comment/comment.component.html
  projects/media-viewer/src/lib/annotations/tags/tags.component.html
  projects/media-viewer/src/lib/toolbar/highlight-toolbar/highlight-toolbar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.html
  projects/media-viewer/src/lib/toolbar/redaction-search-bar/redaction-search-bar.component.spec.ts
  projects/media-viewer/src/lib/toolbar/search-bar/search-bar.component.html
  src/app/app.component.spec.ts
  src/app/media-viewer-wrapper/custom-toolbar/search-bar/search-bar.component.html
  yarn.lock
Labels: ns:em, prd:em, enable_keep_helm, rel:em-media-viewer-pr-1170

#1177 exui-3168-security-scan-issue
  audit.json
Labels: ns:em, prd:em, rel:em-media-viewer-pr-1177
